In [1]:
import csv
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
plt.style.use('classic')
%matplotlib inline
pd.set_option('display.max_rows', None)

In [2]:
df_train1 = pd.read_csv('Data/X_trainData_1.csv')
df_train2 = pd.read_csv('Data/Y_trainData_1.csv')

In [3]:
#temp = df_train1.isin([0]).sum(axis=0)
#temp

In [4]:
#output = df_train2.drop_duplicates()
#output.groupby('Unnamed: 0').size()
print(df_train1.shape)
print(df_train2.shape)

(3393, 222)
(3393, 11)


In [39]:
X = df_train1
y = df_train2['RIF']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [40]:
#plt.plot(range(1,3394), X['DEL_CF_4408101_d102C_34_gid'])
#plt.xticks(np.arange(1,3394,200))
#plt.yticks(np.arange(-2,2))

In [58]:
svclassifier = SVC(C=3.0, kernel='rbf', degree=3, gamma='auto')
svclassifier.fit(X_train, y_train)

SVC(C=3.0, gamma='auto')

In [59]:
y_pred = svclassifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[  0   2  10]
 [  0 241  26]
 [  0   8 392]]
              precision    recall  f1-score   support

          -1       0.00      0.00      0.00        12
           0       0.96      0.90      0.93       267
           1       0.92      0.98      0.95       400

    accuracy                           0.93       679
   macro avg       0.63      0.63      0.63       679
weighted avg       0.92      0.93      0.92       679



/home/abhishek/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
